POST http://localhost:4000/api/likes/addRemove/644aedace62d6eb764d77784
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGM3ZTczNzFlMzU4MWNhYzIzYWE4N2YiLCJmaXJzdE5hbWUiOiJTdGV2YW5TIiwibGFzdE5hbWUiOiJTdGV2YW5vdmljUyIsInJvbGUiOiJhZG1pbiIsInRpbWUiOjE2OTU4NTE3ODEzMjEsImlhdCI6MTY5NTg1MTc4MSwiZXhwIjoxNjk1OTM4MTgxfQ.3nhSydsX6y2NH3qPtXmij1FTPc4T77gAujxwLyynmh4