### GET ALL USERS
GET http://localhost:4000/api/user

### ADD USER
POST http://localhost:4000/api/user/add
Content-Type: application/json

{
    "firstName": "Stevan",
    "lastName": "Stevanovic"
}

### UPDATE USER
PUT http://localhost:4000/api/user/update/123
Content-Type: application/json

{
    "firstName": "Stevan",
    "lastName": "Stevanovic"
}