### GET ALL USERS
GET http://localhost:4000/api/user

### GET USER
GET http://localhost:4000/api/user/64c03f8607350ca3fe59bd2c

### ADD USER
POST http://localhost:4000/api/user/add
Content-Type: application/json

{
    "firstName": "Stevan",
    "lastName": "Stevanovic"
}

### UPDATE USER
PUT http://localhost:4000/api/user/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGM3ZTczNzFlMzU4MWNhYzIzYWE4N2YiLCJmaXJzdE5hbWUiOiJTdGV2YW4yIiwibGFzdE5hbWUiOiJTdGV2YW5vdmljMiIsInJvbGUiOiJhZG1pbiIsInRpbWUiOjE2OTIyMDI5NTg0MzUsImlhdCI6MTY5MjIwMjk1OCwiZXhwIjoxNjkyMjg5MzU4fQ.bLkWPA7xthJBVKP8SLdAct20nJoteCIijUX6R0uW2nE

{
    "firstName": "StevanS",
    "lastName": "StevanovicS"
}