### GET ALL USERS
GET http://localhost:4000/api/user

### GET USER
GET http://localhost:4000/api/user/64c03f8607350ca3fe59bd2c

### ADD USER
POST http://localhost:4000/api/user/add
Content-Type: application/json

{
    "firstName": "Stevan",
    "lastName": "Stevanovic"
}

### UPDATE USER
PUT http://localhost:4000/api/user/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGM3ZTczNzFlMzU4MWNhYzIzYWE4N2YiLCJmaXJzdE5hbWUiOiJTdGV2YW5TIiwibGFzdE5hbWUiOiJTdGV2YW5vdmljUyIsInJvbGUiOiJhZG1pbiIsInRpbWUiOjE2OTM0MzE4NTg0NjEsImlhdCI6MTY5MzQzMTg1OCwiZXhwIjoxNjkzNTE4MjU4fQ.-sWkZDAPt4DIMoEYVc0Rfdr0B9V2ZZLYyTA4ZHsutB4

{
    "firstName": "StevanS",
    "lastName": "StevanovicS"
}

### UPDATE USER BY ID
PUT http://localhost:4000/api/user/update/644a553656f68374bf7964a5
Content-Type:application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGM3ZTczNzFlMzU4MWNhYzIzYWE4N2YiLCJmaXJzdE5hbWUiOiJTdGV2YW5TIiwibGFzdE5hbWUiOiJTdGV2YW5vdmljUyIsInJvbGUiOiJhZG1pbiIsInRpbWUiOjE2OTM1MTcyODYyODcsImlhdCI6MTY5MzUxNzI4NiwiZXhwIjoxNjkzNjAzNjg2fQ.6-ivscnWRQ1ZurQtfVbNZcq4yuirmT8QpsNlQWlL8RQ

{
    "firstName": "StevanS2",
    "lastName": "StevanovicS2",
    "gender": "male",
    "role": "admin"
}